export const CHAPTERS = {
    Math: [
        { n: "Adding up to 20", e: "➕", award: "Plus Pilot", req: 50, details: "Basic addition within 20, including word problems and missing addends." },
        { n: "Subtraction Fun", e: "➖", award: "Minus Maven", req: 50, details: "Subtracting within 20, understanding the relationship between addition and subtraction." },
        { n: "2D & 3D Shapes", e: "📐", award: "Shape Shifter", req: 40, details: "Identifying attributes of triangles, squares, cubes, and spheres." },
        { n: "Patterns & Logic", e: "🧶", award: "Pattern Princess", req: 40, details: "Completing visual and numerical sequences (AB, ABC, and growing patterns)." },
        { n: "Place Value", e: "🔢", award: "Digit Diva", req: 50, details: "Understanding Tens and Ones; identifying the value of a digit in a 2-digit number." },
        { n: "Mental Math", e: "🥷", award: "Number Ninja", req: 40, details: "Quickly adding or subtracting 10 or 1 from any given 2-digit number." },
        { n: "Word Puzzles", e: "🧠", award: "Logic Lady", req: 40, details: "Solving real-world math scenarios requiring one-step addition or subtraction." },
        { n: "Hidden Numbers", e: "🪄", award: "Math Magician", req: 40, details: "Finding the unknown number in an equation like 8 + ? = 15." },
        { n: "Skip Counting", e: "👑", award: "Equation Queen", req: 50, details: "Counting by 2s, 5s, and 10s up to 100." },
        { n: "Group Counting", e: "🧛‍♀️", award: "Countess of Count", req: 50, details: "Introduction to even and odd numbers; pairing objects." },
        { n: "Graph Reading", e: "🔍", award: "Data Detective", req: 40, details: "Interpreting simple pictographs and bar graphs with up to 4 categories." },
        { n: "Half & Quarter", e: "🧚‍♀️", award: "Fraction Fairy", req: 40, details: "Partitioning circles and rectangles into two and four equal shares." },
        { n: "Large Numbers", e: "🏔️", award: "Summit Solver", req: 50, details: "Comparing two-digit numbers using <, >, and = symbols." },
        { n: "Measuring Fun", e: "💎", award: "Geometry Gem", req: 40, details: "Measuring lengths using non-standard units (paperclips) and standard inches/cm." },
        { n: "Liquid Math", e: "🧜‍♀️", award: "Math Mermaid", req: 40, details: "Estimating and comparing volumes (full, half-full, empty)." },
        { n: "Grid Logic", e: "👾", award: "Pixel Plotter", req: 40, details: "Navigating a coordinate-like grid and identifying positions (top-left, 2-right)." },
        { n: "Coordinate Fun", e: "🌌", award: "Galaxy Grapher", req: 40, details: "Simple maps and identifying locations on a 3x3 or 4x4 grid." },
        { n: "Time & Clock", e: "🦄", award: "Unit Unicorn", req: 50, details: "Telling time to the hour and half-hour on analog and digital clocks." },
        { n: "Even & Odd", e: "🤝", award: "Prime Pal", req: 50, details: "Determining whether a group of objects (up to 20) has an odd or even number of members." },
        { n: "Endless Numbers", e: "♾️", award: "Infinite Idol", req: 60, details: "Introduction to three-digit numbers (100-120) and basic regrouping concepts." }
    ],
    Geography: [
        { n: "Map Reading Basics", e: "🗺️", award: "Navigator", req: 40, details: "Understanding legends, scales, and compass roses." },
        { n: "Latitude & Longitude", e: "🌐", award: "Coordinate Captain", req: 40, details: "Finding locations using global coordinates." },
        { n: "Earth's Layers", e: "🌍", award: "Geology Gen", req: 40, details: "Crust, mantle, outer and inner core properties." },
        { n: "Plate Tectonics", e: "🌋", award: "Quake Queen", req: 40, details: "How continents move; earthquakes and volcanoes." },
        { n: "Weathering & Erosion", e: "🏜️", award: "Rock Ranger", req: 30, details: "How wind and water shape the land over time." },
        { n: "The Water Cycle", e: "💧", award: "Hydro Hero", req: 40, details: "Evaporation, condensation, precipitation, collection." },
        { n: "Climate Zones", e: "❄️", award: "Climate Commander", req: 40, details: "Tropical, temperate, and polar regions." },
        { n: "Biomes of the World", e: "🌴", award: "Biome Boss", req: 40, details: "Rainforests, deserts, tundras, and grasslands." },
        { n: "Natural Resources", e: "💎", award: "Resource Rookie", req: 30, details: "Renewable vs. non-renewable resources." },
        { n: "Population & Settlement", e: "🏘️", award: "City Planner", req: 30, details: "Why people live where they do; urban vs rural." },
        { n: "North America", e: "🗽", award: "Western Wanderer", req: 40, details: "Major countries, physical features, and landmarks." },
        { n: "South America", e: "🦜", award: "Amazon Ace", req: 40, details: "The Andes, Amazon Rainforest, and cultures." },
        { n: "Europe", e: "🏰", award: "Euro Expert", req: 40, details: "Peninsulas, history, and diverse nations." },
        { n: "Asia", e: "🐉", award: "Eastern Explorer", req: 50, details: "Himalayas, major rivers, and vast populations." },
        { n: "Africa", e: "🦁", award: "Safari Scout", req: 50, details: "Sahara Desert, Savanna, and Nile River." },
        { n: "Australia & Oceania", e: "🦘", award: "Outback Operator", req: 30, details: "The Great Barrier Reef and island nations." },
        { n: "Antarctica", e: "🐧", award: "Polar Pioneer", req: 30, details: "The frozen continent and scientific research." },
        { n: "Oceans & Seas", e: "🌊", award: "Marine Master", req: 40, details: "The 5 oceans and major seas of the world." },
        { n: "Human Impact", e: "♻️", award: "Eco Guardian", req: 40, details: "Pollution, conservation, and sustainable living." },
        { n: "Global Trade", e: "🚢", award: "Trade Tycoon", req: 40, details: "Imports, exports, and how goods move around the world." }
    ],
    Science: [
        { n: "Space Travel", e: "🚀", award: "Rocket Ranger", req: 40, details: "Identifying components of the solar system (Sun, Earth, Moon)." },
        { n: "Fossils", e: "🦖", award: "Dino Digger", req: 40, details: "Basic understanding of dinosaurs and how we learn from fossils." },
        { n: "The Planets", e: "🔭", award: "Star Gazer", req: 30, details: "Recognizing the 8 planets and their unique characteristics (e.g., Saturn's rings)." },
        { n: "Little Bugs", e: "🐜", award: "Atom Ant", req: 40, details: "Identifying insect body parts (head, thorax, abdomen) and life cycles." },
        { n: "Garden Secrets", e: "🍃", award: "Nature Ninja", req: 40, details: "Understanding what plants need to grow (water, light, air, soil)." },
        { n: "Lab Experiments", e: "🦁", award: "Lab Lion", req: 40, details: "Basic safety and naming common tools (magnifying glass, beaker)." },
        { n: "Watching Clouds", e: "☁️", award: "Cloud Catcher", req: 30, details: "Identifying basic cloud types and what they mean for the weather." },
        { n: "Deep Sea Life", e: "🌊", award: "Ocean Oracle", req: 40, details: "Categorizing ocean animals and identifying salt vs. fresh water." },
        { n: "Sunshine Power", e: "☀️", award: "Solar Sister", req: 30, details: "How the sun provides heat and light and affects the seasons." },
        { n: "Lava Flows", e: "🌋", award: "Volcano Viper", req: 40, details: "Understanding the Earth's layers and basic volcano concepts." },
        { n: "Magnet Pull", e: "🧲", award: "Magnet Mate", req: 40, details: "Testing materials for magnetic properties; North and South poles." },
        { n: "Electric Sparks", e: "⚡", award: "Spark Spirit", req: 30, details: "Basic static electricity and safety with household electricity." },
        { n: "Ladybug Life", e: "🐞", award: "Bug Boss", req: 40, details: "The life cycle of a ladybug and its role in a garden." },
        { n: "Our Planets", e: "🪐", award: "Planet Pilot", req: 40, details: "Comparing rocky planets vs. gas giants." },
        { n: "Flower Growing", e: "🌸", award: "Flora Friend", req: 30, details: "Identifying parts of a flower (petal, stem, leaf, root)." },
        { n: "Saving Earth", e: "♻️", award: "Eco Expert", req: 40, details: "The 3 Rs: Reduce, Reuse, Recycle." },
        { n: "Rainy Days", e: "⛈️", award: "Weather Witch", req: 40, details: "Identifying storm types and severe weather safety." },
        { n: "Falling Apples", e: "🍎", award: "Gravity Girl", req: 30, details: "The concept of gravity and why things fall down." },
        { n: "Body Building", e: "🧬", award: "Cell Celeb", req: 40, details: "Identifying major internal organs (heart, lungs, brain) and their functions." },
        { n: "Master Scientist", e: "🧪", award: "Science Sage", req: 50, details: "States of matter: Solids, Liquids, and Gases." }
    ],
    Words: [
        { n: "Letters", e: "🦁", award: "Letter Lion", req: 60, details: "Vowels vs. Consonants; long and short vowel sounds." },
        { n: "Writing", e: "📖", award: "Story Spinner", req: 50, details: "Identifying the beginning, middle, and end of a story." },
        { n: "Spelling Bee", e: "🐝", award: "Spelling Bee", req: 50, details: "Common Grade 2 sight words and phonics-based spelling." },
        { n: "Grammar Great", e: "✍️", award: "Grammar Great", req: 50, details: "Capitalizing names, dates, and the start of sentences." },
        { n: "Word Wizard", e: "🧙", award: "Word Wizard", req: 40, details: "Understanding compound words (sun + flower = sunflower)." },
        { n: "Poem Princess", e: "📜", award: "Poem Princess", req: 40, details: "Identifying rhyming words and basic rhythm in text." },
        { n: "Vowel Valet", e: "🅰️", award: "Vowel Valet", req: 40, details: "Silent 'e' patterns (CVCe) and vowel teams (ai, ea, ou)." },
        { n: "Rhyme Rider", e: "🏇", award: "Rhyme Rider", req: 40, details: "Creating word families based on endings (-at, -ing, -ight)." },
        { n: "Book Bound", e: "📚", award: "Book Bound", req: 50, details: "Identifying the author, illustrator, and table of contents." },
        { n: "Sentence Star", e: "🌟", award: "Sentence Star", req: 50, details: "Distinguishing between telling and asking sentences." },
        { n: "Verb Viper", e: "🐍", award: "Verb Viper", req: 40, details: "Identifying action words and basic past/present tense." },
        { n: "Noun Knight", e: "🛡️", award: "Noun Knight", req: 40, details: "Common vs. Proper nouns; singular vs. plural." },
        { n: "Adjective Ace", e: "🎨", award: "Adjective Ace", req: 40, details: "Using describing words for size, color, and shape." },
        { n: "Chapter Champ", e: "🔖", award: "Chapter Champ", req: 40, details: "Basic reading comprehension: finding the 'Who' and 'Where'." },
        { n: "Prose Pro", e: "🖋️", award: "Prose Pro", req: 40, details: "Using transition words (First, Next, Last) in a sequence." },
        { n: "Idiom Idol", e: "🎭", award: "Idiom Idol", req: 40, details: "Introduction to simple similes (as busy as a bee)." },
        { n: "Syntax Siren", e: "🧜‍♀️", award: "Syntax Siren", req: 40, details: "Fixing run-on sentences and fragments." },
        { n: "Lexicon Lass", e: "📔", award: "Lexicon Lass", req: 40, details: "Using a dictionary to find words in alphabetical order." },
        { n: "Phonics Phenom", e: "📣", award: "Phonics Phenom", req: 40, details: "Blending sounds and identifying digraphs (ch, sh, th, ph)." },
        { n: "Wisdom Writer", e: "🦉", award: "Wisdom Writer", req: 50, details: "Using context clues to find the meaning of unknown words." }
    ],
    World: [
        { n: "Directions", e: "🗺️", award: "Map Master", req: 30, details: "Cardinal directions: North, South, East, West." },
        { n: "Countries", e: "🚩", award: "Flag Finder", req: 40, details: "Recognizing shapes and colors of famous world flags." },
        { n: "The Globe", e: "🌍", award: "Globe Trotter", req: 30, details: "Identifying the 7 continents and 5 oceans." },
        { n: "City Captain", e: "🏙️", award: "City Captain", req: 30, details: "Urban vs. Rural environments; basic city features." },
        { n: "River Rider", e: "🚣", award: "River Rider", req: 30, details: "Important world rivers (Nile, Amazon, Ganges) and their uses." },
        { n: "Mountain Muse", e: "🏔️", award: "Mountain Muse", req: 30, details: "Famous mountain ranges (Himalayas, Andes) and heights." },
        { n: "Desert Dreamer", e: "🏜️", award: "Desert Dreamer", req: 30, details: "Life in the desert; plant and animal adaptations." },
        { n: "Island Idol", e: "🏝️", award: "Island Idol", req: 30, details: "Definition of an island and famous examples." },
        { n: "Culture Curator", e: "🏮", award: "Culture Curator", req: 30, details: "Major world festivals and traditions (Diwali, Eid, Christmas, Hanukkah)." },
        { n: "History Hero", e: "🏛️", award: "History Hero", req: 40, details: "Timelines: Past, Present, and Future." },
        { n: "Capital Chief", e: "🏛️", award: "Capital Chief", req: 30, details: "Matching major countries with their capital cities." },
        { n: "Border Boss", e: "🛂", award: "Border Boss", req: 30, details: "Understanding what a country is and how people travel." },
        { n: "Landmark Lady", e: "🗼", award: "Landmark Lady", req: 30, details: "Identifying the Eiffel Tower, Great Wall, and Taj Mahal." },
        { n: "Safari Star", e: "🦒", award: "Safari Star", req: 30, details: "Animals of the Savannah and African geography." },
        { n: "Arctic Ally", e: "🧊", award: "Arctic Ally", req: 30, details: "Geography of the North and South Poles." },
        { n: "Jungle Joy", e: "🌴", award: "Jungle Joy", req: 30, details: "Layers of the rainforest and its importance." },
        { n: "Summit Seeker", e: "🧗", award: "Summit Seeker", req: 30, details: "Highest points on each continent." },
        { n: "Voyage Val", e: "🚢", award: "Voyage Val", req: 30, details: "Modes of international travel: Air vs. Sea." },
        { n: "Compass Queen", e: "🧭", award: "Compass Queen", req: 30, details: "How a compass works and identifying intermediate directions (NE, SE, etc.)." },
        { n: "Peace Pilot", e: "🕊️", award: "Peace Pilot", req: 40, details: "Global citizens: How children around the world are the same and different." }
    ],
    GK: [
        { n: "The Indian Constitution", e: "📜", award: "Constitution Champ", req: 40, details: "Preamble analysis, Fundamental Rights (Articles 12-35), Fundamental Duties, and the role of the Drafting Committee led by Dr. Ambedkar." },
        { n: "State Government Functions", e: "🏛️", award: "State Strategist", req: 40, details: "Roles of the Governor, CM, and Council of Ministers; difference between Vidhan Sabha and Vidhan Parishad; legislative process at state level." },
        { n: "Women Pioneers & Reformers", e: "👩‍🏫", award: "Reform Ranger", req: 40, details: "History of the women's movement; icons like Savitribai Phule, Rashsundari Devi, and modern achievers; legal protections like the 73rd Amendment." },
        { n: "The Indian Judicial System", e: "⚖️", award: "Justice Judge", req: 40, details: "Hierarchy of courts (Supreme, High, District); PIL (Public Interest Litigation); FIR process; independent judiciary and Article 21." },
        { n: "India in Space (ISRO 2026)", e: "🚀", award: "Space Scout", req: 40, details: "Gaganyaan G1 uncrewed mission (March 2026) with Vyommitra robot; Chandrayaan-3 legacy; Aditya-L1 solar studies; LVM3 rocket technology." },
        { n: "Renewable Energy & Sustainability", e: "☀️", award: "Green Guardian", req: 40, details: "India's 500GW non-fossil goal by 2030; status as 3rd largest solar market; National Green Hydrogen Mission; solar-powered EV charging infrastructure." },
        { n: "Cyber Safety & Digital Literacy", e: "💻", award: "Cyber Sentinel", req: 40, details: "Digital footprints; privacy settings on social media; identifying phishing and cyber-bullying; safe use of UPI and digital payments." },
        { n: "Artificial Intelligence (AI)", e: "🤖", award: "AI Ace", req: 40, details: "Basic AI concepts; impact of Generative AI (like ChatGPT); AI in healthcare and education; ethical use of technology." },
        { n: "Sustainable Development Goals", e: "🌱", award: "SDG Scholar", req: 40, details: "The 17 UN SDGs to be achieved by 2030; India's progress in 'No Poverty', 'Quality Education', and 'Climate Action'." },
        { n: "The Himalayan Ecosystem", e: "🏔️", award: "Highland Hero", req: 40, details: "Physical geography of the Himalayas; importance of glaciers as water towers; impact of climate change on mountain biodiversity." },
        { n: "Major World Rivers", e: "🌊", award: "River Runner", req: 40, details: "Importance of the Nile, Amazon, and Yangtze; India's Ganga-Brahmaputra system; river pollution and rejuvenation projects (Namami Gange)." },
        { n: "Wildlife Conservation in India", e: "🐅", award: "Wildlife Warden", req: 40, details: "Project Tiger and Project Elephant; National Parks vs. Sanctuaries; endangered species like the Snow Leopard and Great Indian Bustard." },
        { n: "Medieval India Highlights", e: "🏰", award: "History Hunter", req: 40, details: "The Delhi Sultanate (Razia Sultan); Mughal Empire architecture; the rise of the Marathas under Shivaji Maharaj." },
        { n: "Classical Dances & Culture", e: "💃", award: "Culture Captain", req: 40, details: "The 8 Indian classical dances; states of origin (e.g., Kathak-UP, Mohiniyattam-Kerala); intangible cultural heritage recognized by UNESCO." },
        { n: "Bhakti & Sufi Movements", e: "🪕", award: "Soul Seeker", req: 40, details: "Teachings of saints like Mirabai, Kabir, and Guru Nanak; the message of social equality and devotion over rituals." },
        { n: "Basic Economics & RBI", e: "💰", award: "Econ Expert", req: 40, details: "Role of the Reserve Bank of India; understanding inflation; the transition from barter to digital currency; GST basics." },
        { n: "International Organizations", e: "🇺🇳", award: "Global Guardian", req: 40, details: "Roles of the UN, WHO, and UNESCO; India's G20 Presidency legacy; BRICS and Quad alliances." },
        { n: "Literature & Famous Authors", e: "🖋️", award: "Literary Legend", req: 40, details: "Works of Rabindranath Tagore; modern literature by Sudha Murty and Arundhati Roy; the significance of the Jnanpith Award." },
        { n: "Sports Icons & Achievements", e: "🏅", award: "Sports Star", req: 40, details: "India's performance in recent Olympics/Paralympics; rise of the WPL (Women’s Premier League); icons like Neeraj Chopra and P.V. Sindhu." },
        { n: "Health, Wellness & Nutrition", e: "🧘", award: "Wellness Warrior", req: 40, details: "The science of Yoga and Pranyama; benefits of millets (Shree Anna); mental health awareness and balanced lifestyles for teenagers." }
    ]
};
